#calculate the probability of loop lengths 

dloop <- function(n, nreps) {
  each_loop_lengths <- c() #list to store the loop lengths generated by all simulations
  max_loop_lengths <- c()
  
  for (i in 1:nreps){ 
    #simulate the boxes nreps times 
    boxes <- sample(1 : (2*n), 2*n , replace=FALSE) 
    unopened_boxes <- 1:(2*n)
    
    new_each_loop_lengths <- c() #store the unique loop lengths in each simulation 
    new_max_loop_lengths <- c()
    
    while (length(unopened_boxes) > 2 ){ #while more than 2 boxes are still closed, indexing breaks down for smaller loops
      #pick the smallest number unopened box and store the value of the card inside 
      cards_picked <- boxes[unopened_boxes[1]]
      #pick your next box according to your last card and scan each closed loop
      for (b in 2:length(unopened_boxes)){ #max loop length is the number of closed boxes
        cards_picked <- c(cards_picked, boxes[cards_picked[b-1]])
      }#end for 
      #add your loop length to your list
      
      new_each_loop_lengths <- c(new_each_loop_lengths, length(unique(cards_picked))) 
      
      
      #remove the boxes opened 
      unopened_boxes <- setdiff(unopened_boxes,unique(cards_picked))
    } #end while 
    
    each_loop_lengths <- c(each_loop_lengths, unique(new_each_loop_lengths))
    max_loop_lengths <- c(max_loop_lengths, max(new_each_loop_lengths))
    
  } #end for 
  
  #probability vector for the occurance of each type of loop length 
  prob_vec_y <- tabulate(each_loop_lengths)/nreps
  
  
  #probability vector for the occurance of each maximum loop length 
  prob_vec_ymax <- tabulate(max_loop_lengths)/nreps
  x_axis <- 1:length(prob_vec_ymax)
  plot(x_axis, prob_vec_ymax, xlab = "max loop length", ylab = "probability")
  prob_less_n_loop = sum(prob_vec_y[1:n])
  cat("\n","prob your max loop has a length less than n",   prob_less_n_loop, "\n")
  return(prob_vec_y)
}#end function


start_time = Sys.time()
VAR_1 <- dloop(50, 10000)
end_time = Sys.time()
cat(time_taken = end_time - start_time)
VAR_1

print(sum(VAR_1))



