#calculate the probability of loop lengths 

dloop <- function(n, nreps) {
  all_loop_lengths <- c() #list to store the loop lengths generated by all simulations
  
  for (i in 1:nreps){ 
    #simulate the boxes nreps times 
    boxes <- sample(1 : (2*n), 2*n , replace=FALSE) 
    unopened_boxes <- 1:(2*n)
    new_loop_lengths <- c() #store the unique loop lengths in each simulation 
    
    while (length(unopened_boxes) > 2 ){ #while more than 2 boxes are still closed, indexing breaks down for smaller loops
      #pick the smallest number unopened box and store the value of the card inside 
      cards_picked <- boxes[unopened_boxes[1]]
      #pick your next box according to your last card and scan each closed loop
      for (b in 2:length(unopened_boxes)){ #max loop length is the number of closed boxes
        cards_picked <- c(cards_picked, boxes[cards_picked[b-1]])
      }#end for 
      #add your loop length to your list
      new_loop_lengths <- c(new_loop_lengths, length(unique(cards_picked))) 
      #remove the boxes opened 
      unopened_boxes <- setdiff(unopened_boxes,unique(cards_picked))
    } #end while 
    all_loop_lengths <- c(all_loop_lengths, max(new_loop_lengths))
    
  } #end for 
  #hist(loop_lengths)
  prob_vec_y <- tabulate(all_loop_lengths)/nreps
  x_axis <- 1:length(prob_vec_y)
  plot(x_axis, prob_vec_y, xlab = "max loop length", ylab = "probability")
  prob_less_n_loop = sum(prob_vec_y[1:n])
  cat("\n",   prob_less_n_loop, "\n")

  return(prob_vec_y)
}#end function


dloop(10, 500)


